lua/undo-glow/init.lua
This error can be reproduced by go to the end of the buffer and enter a
couple of new line and perform undo or redo. This pr make sure to
sanitize and make sure no out-of-range arguments are passed to extmarks.
=> fix: add coordinates sanitization to prevent out-of-range errors. Closes #9

README.md, lua/undo-glow/init.lua
Unifying the logic of how undo-glow works when highlighting. Instead of
separated API, we unify all of them together in a single function.
The `attached_and_run` function can now be used to:
- Create action for keymap binding
- Create autocmd
=> feat!: remove track_changes and merge into attach_and_run

README.md, lua/undo-glow/init.lua
If no fg passed to the color, will just remain the existing editor color
for the text.
=> feat: make fg optional

lua/undo-glow/animation.lua, lua/undo-glow/callback.lua
If config.animation is off, we should just use the existing hlgroup.
unique_hlgroups is only needed to dynamically create color groups during
animation. We cannot just overwrite the existing hlgroup because undo
and redo operations sometimes are performed in a quick manner and all
the colors for each operation will be in a state of clashing with each
other.
=> fix: do not use unique_hlgroup if config.animation is off

lua/undo-glow/utils.lua
When redo or undo, if the last line is included it will be ignored.
Do not remove one line in `sanitize_coords` if last line for both `s_row` and `e_row`
=> fix: fix ignored end of line

README.md, doc/undo-glow.nvim.txt, lua/undo-glow/config.lua, lua/undo-glow/init.lua
While adding more built-in actions with different hlgroup, instead of
listing out all of the options in config, I think moving into a table is
a better choice. Please read the docs on how to set it up.
No errors will be thrown if you're using old config. The colors will
just fall back to default until you change them.
=> feat!: Move highlights config into table

README.md, doc/undo-glow.nvim.txt, lua/undo-glow/commands.lua, lua/undo-glow/init.lua
Apperently running commands outside of the attach function is more
reliable. Since this changes, I decided to rename the API to
`highlight_changes` instead of `attach_and_run`, which is more
appropriate consider what it does now.
=> feat!: move cmd out from attach function

lua/undo-glow/highlight.lua, lua/undo-glow/utils.lua
This fix will allow users to set the hlgroups outside of the plugin.
E.g. `Snacks.util.set_hl({ UgYank = "Cursor" }, { default = true })`, it
should still work and grabbing the right colors after this change.
=> fix: follow linked hlgroups instead of ignore

lua/undo-glow/commands.lua
This fix should avoid error throwing when the search is empty and trying
to next or prev.
=> fix: add protected call for vim.cmd for search commands

README.md, doc/undo-glow.nvim.txt, lua/undo-glow/animation.lua, lua/undo-glow/config.lua, lua/undo-glow/init.lua, lua/undo-glow/utils.lua
Since animation can be configured everywhere, it is easier and nicer to
set in it it's own table for more clarity. Furthermore animation is now
off by default. You need to explicitly turn it on globally or per action
basis.
=> feat!: move animation related opts to animation key

README.md, doc/undo-glow.nvim.txt, lua/undo-glow/animation.lua, lua/undo-glow/config.lua, lua/undo-glow/init.lua, lua/undo-glow/utils.lua
This changes allow string or function to be passed to the easing
configuration opts. This means that we do not need to have additional
config and can set everything within opts.
=> feat: refactor easings for better opts setup

lua/undo-glow/utils.lua, tests/utils_spec.lua
This should fix the error when `_` is interpreted as 0 instead of {} or
nil when using the function, since opts is optional.
=> fix(utils.merge_command_opts): make sure opts are always table

lua/undo-glow/utils.lua
This change fixes the issue where previously only 'exact' case will
highlight.
=> fix(utils.search): parse lines and patterns in lowercase

doc/undo-glow.nvim.txt, lua/undo-glow/utils.lua
Previously, M.get_search_star_region always returned the first match in
the line, regardless of the cursor's position. This commit updates the
function to slice the line from the current cursor column, so it
correctly finds the next match on the same line.
=> fix(utils.get_search_star_region): start search from cursor column to return next match

README.md, doc/undo-glow.nvim.txt, lua/undo-glow/animation.lua, lua/undo-glow/config.lua, lua/undo-glow/health.lua, lua/undo-glow/types.lua, lua/undo-glow/utils.lua, tests/animation_spec.lua, tests/utils_spec.lua
This change will allow to scope highlights to only current window to
reduce noises. However, please note that this is utilising an
experimental extmark option `scoped`. Not sure if there will be any
regression considering different neovim version are out there...
=> feat: add ability to scope highlights to current window only

lua/undo-glow/types.lua
This is not needed to pass from outer functions. The internal will
create the right ns as going.
=> fix(types): make ns optional for handle_highlight function

doc/undo-glow.nvim.txt, lua/undo-glow/health.lua, lua/undo-glow/utils.lua
Upon diving deep into the source, 0.11 doesn't
`vim.api.nvim__win_add_ns` anymore. I think `vim.api.nvim__ns_set` might
be the equivalent for it. Not so sure as nightly doesn't have good docs.
It's current working fine for nightly version
`v0.11.0-dev-1912+g0c0352783f`. Keep an eye on future nightly releases
as the API might be changing anytime soon or never.
=> fix(utils.create_extmark_opts): different API for setting windown namespace for nightly and stable

lua/undo-glow/animation.lua
This change might fix the weird error where when you copy and paste full
document text, it might throw `end_col` exceeded error. Maybe fixed it
but not sure, let's see.
=> fix(animation.slide): add pcall for setting extmark

lua/undo-glow/animation.lua
Error to reproduce:
1. set `slide` to `cursor_moved` animation
2. add `cursor_moved` as an autocmd for `CursorMoved` event
3. prepare a buffer that has more than 20+ lines of code, and then yank
any 2 or above lines
4. quickly do `gg<S-v>G` to select all and `p` or `d` to paste the previous
yanked lines (Need to be very quick, it does'n happen if you slowly
select all and paste in a slow pace)
5. gets `end_col` is out of range error
---
This error happens because the slide animation are running both when you
select from top to bottom (more than 10 lines) and then when pasting the
yanked lines (replace the whole document with the yanked lines and
causes another 10 lines jump). Now it will try to run animation on the
end of the buffer (before paste) and without waiting for the animation, …
=> fix(animation.slide): fixes end_col out of range error in certain cases

doc/undo-glow.nvim.txt, lua/undo-glow/animation.lua
This change should fix the issue where when we have multiple different
buffers opened, and also using cursor moved with slide animation, when
switching the buffer quickly, it will throw an error of `ns_id` is
invalid.
In this case, we added protected call to `del_extmark` in
`animate_clear` and do not fallback to `fade` animation when it could
not create an `extmark` in `slide` animation.
=> fix(animation.slide): `ns_id` is invalid when switching buffer very quickly

README.md, doc/undo-glow.nvim.txt, lua/undo-glow/animation.lua, lua/undo-glow/callback.lua, lua/undo-glow/config.lua, lua/undo-glow/init.lua, lua/undo-glow/types.lua, lua/undo-glow/utils.lua, tests/utils_spec.lua
Internal functions now retrieve the config directly from config.lua
instead of receiving it via parameters. This change is internal and does
not affect the user API.
=> refactor: move plugin setup to config.lua and update internal config usage

doc/undo-glow.nvim.txt, lua/undo-glow/utils.lua
This util will try to get the start and end position of current cursor
and can be used for highlights. This is useful for integration like
`flash`.
=> fix(utils): add `get_current_cursor_word` utils for integration purpose

lua/undo-glow/animation.lua, lua/undo-glow/utils.lua
Add some check to ensure the string is type 1 (string) instead of type
10 (blob) in certain cases, say binary file. We will just set the line
to "" when it happens, hopefully fixes the case.
=> fix: ensure line are actually string instead of blob before pass to `vim.fn.strdisplay` (fixes #255)

lua/undo-glow/integrations.lua
Abort if package is not callable, meaning that it is not installed. No
need to run the rest of the function.
=> fix(integrations): guard integrations with pcall to package
